Repository Vin205/Enyanjyoti, pull requests merged in 2024-10, with the labels that each got.

#17 ADD FOOTER SECTION TO THE PAGE #14
  src/App.js
  src/Educ.js
  src/Footer.js
  src/Hom.js
  src/Nabar.css
  src/Nabar.js
  src/footer.css
Labels: hacktoberfest-accepted, gssoc-ext, Level1, update

#22 added login signup pages
  package-lock.json
  package.json
  src/App.js
  src/Login.js
  src/Nabar.js
  src/Signup.js
Labels: hacktoberfest-accepted, gssoc-ext, Level1

#23 Update README.md Fixes #6
  README.md
Labels: hacktoberfest-accepted, gssoc-ext, Level1, update

#30 resolved conflict and addressing issue no. #27 corrected typing and change title and favicon from react app
  public/favicon.ico
  public/favicon/android-chrome-192x192.png
  public/favicon/android-chrome-512x512.png
  public/favicon/apple-touch-icon.png
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon.ico
  public/favicon/site.webmanifest
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/App.js
  src/Navbar.css
  src/Navbar.js
Labels: hacktoberfest-accepted, gssoc-ext, Level1, Accepted

#32 Fix: HomePage section repitition is fixed
  src/App.js
Labels: Level2, hacktoberfest-accepted, gssoc-ext, Accepted

#35 FIX THE NAVBAR add Hamburger #13
  src/App.js
Labels: hacktoberfest-accepted, gssoc-ext, Level1, update, Accepted

#36 Fixed the homepage ui #31
  src/App.js
  src/Footer.js
  src/Hom.css
  src/Hom.js
  src/Navbar.css
  src/Navbar.js
  src/footer.css
Labels: hacktoberfest-accepted, gssoc-ext, Level3, Accepted

#45 Add Basic Snapshotting(git status, git commit) , branching and merging commands
  README.md
Labels: hacktoberfest-accepted, gssoc-ext, Level1, Accepted

#46 Added About page with routing and a gallery slider for issue #33
  src/About.css
  src/About.js
  src/App.js
Labels: Level2, hacktoberfest-accepted, gssoc-ext, Accepted

#52 Enhanced the UI of the footer
  package-lock.json
  package.json
  src/Footer.js
  src/footer.css
Labels: hacktoberfest-accepted, gssoc-ext, Level1, Accepted

#54 Update the entire directory structure
  package-lock.json
  package.json
  src/App.js
  src/Craft.js
  src/components/Act/Act.js
  src/components/Car/Car.js
  src/components/Concept/Concep.js
  src/components/Craft/Craft.js
  src/components/Education/Educ.js
  src/components/Firebase/firebase.js
  src/components/Footer/Footer.js
  src/components/Footer/footer.css
  src/components/Loan/Loan.js
  src/components/Login/Login.js
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.js
  src/components/Quiz/Quiz.css
  src/components/Quiz/Quiz.js
  src/components/Register/Register.js
  src/components/Sef/Sef.js
  src/components/Signup/Signup.js
  src/context/AppContext.js
  src/hooks/useCustomHook.js
  src/pages/About/About.css
  src/pages/About/About.js
  src/pages/Contact/Contact.css
  src/pages/Contact/Contact.js
  src/pages/Home/Hom.css
  src/pages/Home/Hom.js
  src/styles/main.css
  src/utils/helpers.js
Labels: Level2, hacktoberfest-accepted, gssoc-ext, Accepted

#60 Additon of All Contributors | Issue #53
  README.md
Labels: hacktoberfest-accepted, gssoc-ext, Level1, Accepted

#63 Issue Title: Add FAQ (Frequently Asked Questions) Page to the Website #38
  src/pages/Home/Faqs.css
  src/pages/Home/Faqs.js
  src/pages/Home/Hom.js
Labels: Level2, hacktoberfest-accepted, gssoc-ext, Accepted

#75 solved issue #47
  frontend/package-lock.json
  frontend/public/index.html
  frontend/src/pages/About/About.css
  frontend/src/pages/About/About.js
  frontend/src/pages/Home/Hom.css
  frontend/src/pages/Home/Hom.js
Labels: hacktoberfest-accepted, gssoc-ext, Level1, Accepted

#76 Added image carousel in about section
  README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/About/About.css
  frontend/src/pages/About/About.js
  frontend/src/pages/Home/Faqs.css
  frontend/src/pages/Home/Hom.css
Labels: Level2, hacktoberfest-accepted, gssoc-ext, Accepted

#78 solved issue #48
  frontend/public/images/moon.png
  frontend/public/images/sun.png
  frontend/src/components/Footer/footer.css
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/Navbar/Navbar.js
  frontend/src/pages/About/About.css
  frontend/src/pages/Home/Faqs.css
  frontend/src/pages/Home/Hom.css
Labels: Level2, hacktoberfest-accepted, gssoc-ext, Accepted

#77 Fix: Replace deprecated middleware options in webpackDevServer.js
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
Labels: Level2, hacktoberfest-accepted, gssoc-ext, Accepted

#64 Updated Responsiveness
  frontend/src/components/Footer/footer.css
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/Navbar/Navbar.js
  frontend/src/pages/Home/Hom.css
Labels: Level2, hacktoberfest-accepted, gssoc-ext, Accepted

#81 solved issue #49
  frontend/src/App.js
  frontend/src/components/Login/Login.js
  frontend/src/components/Signup/Signup.js
Labels: Level2, hacktoberfest-accepted, gssoc-ext, Accepted

#83 FIxed Navbar vertical alignment and Login/Signup Components
  frontend/src/components/Login/Login.js
  frontend/src/components/Navbar/Navbar.js
  frontend/src/components/Signup/Signup.js
Labels: hacktoberfest-accepted, gssoc-ext, Level3, Accepted

#80 added loan section
  frontend/package-lock.json
  frontend/src/App.js
  frontend/src/components/Loan/Loan.js
  frontend/src/components/Navbar/Navbar.js
  frontend/src/pages/Home/Hom.js
  frontend/src/pages/Loan/Loan.css
  frontend/src/pages/Loan/Loan.js
Labels: hacktoberfest-accepted, gssoc-ext, Level3, Accepted

#84 Added a profile card Component
  .gitignore
  README.md
  eslint.config.js
  frontend/src/components/profileCard/ProfileCard.js
  index.html
  package-lock.json
  package.json
Labels: Level2, hacktoberfest-accepted, gssoc-ext, Accepted

#90 solved issue #86
  frontend/src/App.js
  frontend/src/components/Navbar/Navbar.js
Labels: hacktoberfest-accepted, gssoc-ext, Level1, Accepted

#94 solved issue #88
  frontend/src/components/Login/Login.js
  frontend/src/components/Signup/Signup.js
Labels: hacktoberfest-accepted, gssoc-ext, Level1, Accepted

#93 Resize and responsive Cards & Add contact form
  frontend/src/App.js
  frontend/src/components/Navbar/Navbar.js
  frontend/src/pages/Contact/Contact.js
  frontend/src/pages/Home/Hom.js
Labels: Level2, hacktoberfest-accepted, gssoc-ext, Accepted

#97 New Header Component
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/Navbar/Navbar.js
Labels: Level2, hacktoberfest-accepted, gssoc-ext, Accepted

#105 Updated Contributors Profile
  README.md
Labels: hacktoberfest-accepted, gssoc-ext, Level1, Accepted

#101 Implement Login, Signup, and Logout Features with Dashboard Route (Fix #89)
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Firebase/firebase.js
  frontend/src/components/Firebase/logout.js
  frontend/src/components/Firebase/useAuth.js
  frontend/src/components/Login/Login.js
  frontend/src/components/Signup/Signup.js
  frontend/src/pages/Dashboard/Dashboard.js
Labels: hacktoberfest-accepted, gssoc-ext, Level3

#111 added featured in table
  README.md
Labels: hacktoberfest-accepted, gssoc-ext, Level1, Accepted

#113 issue #110 Dockerize the Application
  backend/.dockerignore
  backend/dockerfile
  frontend/.dockerignore
  frontend/dockerfile
Labels: Level2, hacktoberfest-accepted, gssoc-ext, Accepted

#138 Bug/Twitter Icon
  frontend/src/components/Footer/Footer.js
Labels: hacktoberfest-accepted, gssoc-ext, Level1

#131 Fixed the ui of misplacement of showpassword icon
  frontend/src/components/Login/Login.js
  frontend/src/components/Signup/Signup.js
Labels: hacktoberfest-accepted, gssoc-ext, Level1

#127 Fixed Responsiveness of login and signup pages issue #109
  frontend/src/components/Login/Login.js
  frontend/src/components/Signup/Signup.js
Labels: hacktoberfest-accepted, gssoc-ext, Level1

#128 Changed the CSS of the about page and the swiper slide #107
  frontend/src/pages/About/About.css
  frontend/src/pages/About/About.js
Labels: Level2, hacktoberfest-accepted, gssoc-ext, Accepted

#141 BUG: Invalid or wrong path route added
  frontend/src/App.js
  frontend/src/pages/Error/index.js
Labels: Level2, hacktoberfest-accepted, gssoc-ext, Accepted

#143 Bug: Site Icon open in tab
  frontend/src/components/Navbar/Navbar.js
  frontend/src/pages/Home/Hom.css
  frontend/src/pages/Home/Hom.js
Labels: hacktoberfest-accepted, gssoc-ext, Level1, Accepted

#157 enhancement : Align Card Buttons and Improve Animation Scaling on Home page
  frontend/src/pages/Home/Hom.css
  frontend/src/pages/Home/Hom.js
Labels: hacktoberfest-accepted, gssoc-ext, Level1, Accepted

#147 new favicon
  frontend/public/favicon/android-chrome-192x192.png
  frontend/public/favicon/android-chrome-512x512.png
  frontend/public/favicon/apple-touch-icon.png
  frontend/public/favicon/favicon-16x16.png
  frontend/public/favicon/favicon-32x32.png
  frontend/public/favicon/favicon.ico
  frontend/public/favicon/site.webmanifest
  frontend/public/favicons/android-chrome-192x192.png
  frontend/public/favicons/android-chrome-512x512.png
  frontend/public/favicons/apple-touch-icon.png
  frontend/public/favicons/favicon.ico
  frontend/public/favicons/icon.svg
  frontend/public/favicons/manifest.webmanifest
  frontend/public/index.html
Labels: hacktoberfest-accepted, gssoc-ext, Level1, Accepted

#144 add loan option in toggle button
  frontend/src/components/Navbar/Navbar.js
Labels: hacktoberfest-accepted, gssoc-ext, level1, Accepted

#162 Edited ContactUs
  frontend/public/images/contact.jpg
  frontend/src/pages/Contact/Contact.css
  frontend/src/pages/Contact/Contact.js
Labels: hacktoberfest-accepted, gssoc-ext, level1, Accepted

#164 Improve Loan Calculator & Loan Summary Display
  frontend/src/pages/Loan/Loan.css
  frontend/src/pages/Loan/Loan.js
Labels: level2, hacktoberfest-accepted, gssoc-ext, Accepted

#166 Improve the UI of the 404 page
  frontend/src/App.js
  frontend/src/pages/Error/index.js
Labels: level2, hacktoberfest-accepted, gssoc-ext, Accepted

#169 minor changes
  frontend/src/components/Footer/footer.css
  frontend/src/components/Navbar/Navbar.css
  frontend/src/pages/About/About.css
  frontend/src/pages/Contact/Contact.css
  package-lock.json
Labels: hacktoberfest-accepted, gssoc-ext, level3, Accepted

#171 Implement Authentication Routes: Register and Login
  backend/.env
  backend/.env.example
  backend/.gitignore
  backend/READEME.md
  backend/package-lock.json
  backend/package.json
  backend/server.js
  backend/src/constants/index.js
  backend/src/controllers/auth/loginUser.js
  backend/src/controllers/auth/registerUser.js
  backend/src/controllers/index.js
  backend/src/controllers/userController.js
  backend/src/models/User.js
  backend/src/routes/authRoutes.js
  backend/src/routes/userRoutes.js
  backend/src/server.js
Labels: level2, hacktoberfest-accepted, gssoc-ext, Accepted

#176 Enhancement : Improved UI
  frontend/src/pages/Home/Hom.css
  frontend/src/pages/Home/Hom.js
Labels: hacktoberfest-accepted, gssoc-ext, level1, Accepted

#192 Strong password
  frontend/src/components/Signup/Signup.js
Labels: hacktoberfest-accepted, gssoc-ext, level1, Accepted

#194 Enhancements in design of the navbar
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/Navbar/Navbar.js
  frontend/src/pages/Home/Hom.css
Labels: hacktoberfest-accepted, gssoc-ext, level1, Accepted

#196 add input validations
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Login/Login.js
  frontend/src/components/Signup/Signup.js
  frontend/src/validations/validation.js
  package-lock.json
  package.json
Labels: level2, hacktoberfest-accepted, gssoc-ext, Accepted

#206 [feat], [perf] : Changed features of login.js for ease of access
  frontend/src/components/Login/Login.js
Labels: level2, hacktoberfest-accepted, gssoc-ext

#205 Revamped Footer and Navbar for Enhanced User Experience
  frontend/src/components/Footer/footer.css
  frontend/src/components/Navbar/Navbar.css
Labels: level2, hacktoberfest-accepted, gssoc-ext, Accepted

#207 Set Up Husky Pre-Commit Hook and ESLint/Prettier for Backend
  .gitignore
  .husky/pre-commit
  backend/.prettierrc
  backend/READEME.md
  backend/eslint.config.js
  backend/package-lock.json
  backend/package.json
  backend/server.js
  backend/src/constants/index.js
  backend/src/controllers/auth/loginUser.js
  backend/src/controllers/auth/registerUser.js
  backend/src/controllers/index.js
  backend/src/models/User.js
  backend/src/routes/authRoutes.js
  backend/src/utils/db/connectDB.js
  backend/src/utils/index.js
  eslint.config.js
  package-lock.json
  package.json
Labels: level2, hacktoberfest-accepted, gssoc-ext

#213 [Fix]: makes website mobile-responsive
  frontend/src/components/Footer/footer.css
  frontend/src/pages/Home/Hom.css
Labels: level2, hacktoberfest-accepted, gssoc-ext, Accepted

#222 Add GitHub Workflow for Auto-Closing Similar Issue Requests and autolabeler
  .github/workflows/autolabeler.yml
  .github/workflows/restrict_issues.yml
Labels: level2, hacktoberfest-accepted, gssoc-ext

#227 Added the cobtributors page.
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/components/Navbar/Navbar.js
  frontend/src/pages/Contributor/ContributorsPage.jsx
Labels: level2, hacktoberfest-accepted, gssoc-ext, Accepted

#210 Add Contact Us Form, enhance the Footer and also Responsive
  frontend/src/components/Footer/Footer.js
  frontend/src/components/Footer/footer.css
Labels: level2, hacktoberfest-accepted, gssoc-ext, Accepted

#189 Updated the Buttons
  frontend/package-lock.json
  frontend/src/pages/Home/Hom.css
Labels: hacktoberfest-accepted, gssoc-ext, level1, Accepted

#251 UI: Improve the UI of loan page
  frontend/src/pages/Loan/Loan.css
Labels: level2, hacktoberfest-accepted, gssoc-ext, Accepted

#249 BUG: Footer added in login and signup form
  frontend/src/components/Login/Login.js
  frontend/src/components/Signup/Signup.js
Labels: level2, hacktoberfest-accepted, gssoc-ext, Accepted

#271 [Fix] Issue #270 resolved : Improved the Navbar problems
  backend/package-lock.json
  frontend/src/components/Navbar/Navbar.css
  frontend/src/pages/Home/Hom.css
  package-lock.json
Labels: hacktoberfest-accepted, gssoc-ext, level1, Accepted

#258 scroll bar added : Scroll bar added #232 done
  frontend/src/pages/Home/Hom.css
Labels: hacktoberfest-accepted, gssoc-ext, level1

#238 Fix UI Responsiveness and add theme-specific illustrations
  frontend/public/images/career.svg
  frontend/public/images/education.svg
  frontend/public/images/loan_and_grants.svg
  frontend/src/pages/Home/Hom.css
  frontend/src/pages/Home/Hom.js
Labels: level2, hacktoberfest-accepted, gssoc-ext, Accepted

#252 Bug: Input validations in forms
  frontend/package.json
  frontend/src/components/Login/Login.js
  frontend/src/components/Signup/Signup.js
  frontend/src/index.js
Labels: level2, hacktoberfest-accepted, gssoc-ext

#269 Added Google OAuth for login and signup
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/src/components/Firebase/firebase.js
  frontend/src/components/Firebase/logout.js
  frontend/src/components/Firebase/useAuth.js
  frontend/src/components/GoogleButton/GoogleButton.js
  frontend/src/components/Login/Login.js
  frontend/src/components/Signup/Signup.js
Labels: level2, hacktoberfest-accepted, gssoc-ext, Accepted

#268 fix: add hyperlinks to FAQ descriptions and hover effect
  frontend/src/pages/Home/Faqs.css
  frontend/src/pages/Home/Faqs.js
  frontend/src/pages/Home/Faqs.jsx
Labels: level2, hacktoberfest-accepted, gssoc-ext

#245 Revamped the footer, enhace the look and feel of the footer
  frontend/src/components/Footer/Footer.js
  frontend/src/components/Footer/footer.css
Labels: hacktoberfest-accepted, gssoc-ext, level1

#244 Add career page
  frontend/src/pages/career/career.css
  frontend/src/pages/career/career.js
Labels: level2, hacktoberfest-accepted, gssoc-ext, Accepted

#284 Update Loan.css
  frontend/src/pages/Loan/Loan.css
Labels: hacktoberfest-accepted

#304 Bug: Improving Allignment loan Page
  frontend/src/pages/Home/Hom.js
  frontend/src/pages/Loan/Loan.js
Labels: level2, hacktoberfest-accepted, gssoc-ext, Accepted

#305 BUG: Improving the Allignment of ContactUs page
  frontend/src/pages/Contact/Contact.js
Labels: level2, hacktoberfest-accepted, gssoc-ext, Accepted

#317 Fix: Navbar- Active Link and Formatting Issues
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/Navbar/Navbar.js
Labels: hacktoberfest-accepted, gssoc-ext, level1

#309 Alignment of certain part of the website
  frontend/src/components/Footer/footer.css
  frontend/src/pages/Home/Faqs.css
  frontend/src/pages/Home/Hom.css
Labels: hacktoberfest-accepted, gssoc-ext, level1

#342 Updated Faqs.css to enhance the overall UI
  frontend/src/pages/Home/Faqs.css
Labels: hacktoberfest-accepted, gssoc-ext, level1

#337 Implement Real-Time Email Validation for Trusted Domains in Signup Component
  frontend/src/components/Signup/Signup.js
Labels: level2, hacktoberfest-accepted, gssoc-ext, Accepted

#333 Update README.md
  README.md
Labels: hacktoberfest-accepted, gssoc-ext, level1, Accepted

#349 Feat: Adding Issues Templates
  .github/ISSUE_TEMPLATE/bug_report_template.md
  .github/ISSUE_TEMPLATE/custom_issue_template.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
Labels: level2, hacktoberfest-accepted, gssoc-ext, Accepted

#370 Added Animeted Pre Loader : Issue no #343
  frontend/src/App.js
  frontend/src/pages/Preloader/Preloader.css
  frontend/src/pages/Preloader/Preloader.jsx
Labels: hacktoberfest-accepted, gssoc-ext, level1, Accepted

#357 Fixed UI inconsistencies and payment frequency recalculation for the loan calculator
  frontend/src/pages/Loan/Loan.css
  frontend/src/pages/Loan/Loan.js
Labels: level2, hacktoberfest-accepted, gssoc-ext, Accepted

#354 "Frequently Asked Questions" to "FAQs" #341
  frontend/src/pages/Home/Faqs.jsx
Labels: hacktoberfest-accepted, gssoc-ext, level1

#340 Update UI
  frontend/src/pages/Loan/Loan.css
Labels: level2, hacktoberfest-accepted, gssoc-ext

#392 Add Smooth Hover Effects to Contact Form
  frontend/src/pages/Contact/Contact.css
Labels: hacktoberfest-accepted, gssoc-ext, level1

#395 Enhancement: Add hover effect to the main heading for a more dynamic appearance #310
  frontend/src/pages/Home/Hom.css
Labels: hacktoberfest-accepted, gssoc-ext, level1

#398 Improved Message Display and Validate Character Length on "Contact Us" Page
  frontend/src/pages/Contact/Contact.js
Labels: level2, hacktoberfest-accepted, gssoc-ext

#399 Updated Signup.js
  frontend/src/components/Signup/Signup.js
Labels: hacktoberfest-accepted, gssoc-ext, level1

#400 Update Login.js
  frontend/src/components/Login/Login.js
Labels: level2, hacktoberfest-accepted, gssoc-ext

#402 Update Navbar.js
  frontend/src/components/Navbar/Navbar.js
Labels: level2, hacktoberfest-accepted, gssoc-ext

#415 Made Quicklinks in footer functional
  frontend/src/components/Footer/Footer.js
Labels: hacktoberfest-accepted, gssoc-ext, level1

#418 Fixed Inconsistent Alignment of Login and Footer Container
  frontend/src/components/Footer/footer.css
  frontend/src/components/Login/Login.js
Labels: hacktoberfest-accepted, gssoc-ext, level1

#423 Created A Donation page
  Enyanjyoti/Enyanjyoti.html
  Enyanjyoti/button.html
Labels: hacktoberfest-accepted, gssoc-ext, level3

#425 #405 fixed hyperlink buttons
  frontend/src/pages/Home/Hom.css
Labels: hacktoberfest-accepted, gssoc-ext, level1

#467 Updated signup and login page uis
  .gitattributes
  frontend/src/components/GoogleButton/GoogleButton.js
  frontend/src/components/Login/Login.js
  frontend/src/components/Signup/Signup.js
Labels: level2, hacktoberfest-accepted, gssoc-ext

#454 Update Navbar.css
  frontend/src/components/Navbar/Navbar.css
Labels: hacktoberfest-accepted, gssoc-ext, level1

#440 Fixed Contact Us Form Submit Button UI Breaking in Mobile View
  frontend/src/pages/Contact/Contact.css
Labels: hacktoberfest-accepted, gssoc-ext, level1

#439 Fixed Inconsistent Alignment of SignUp and Footer Container
  frontend/src/components/Signup/Signup.js
Labels: hacktoberfest-accepted, gssoc-ext, level1

#482 Update README to Enhance Project Title with GIF for Improved Aesthetics (#453)
  README.md
Labels: hacktoberfest-accepted, gssoc-ext, level1

#471 Update Faqs.css
  frontend/src/pages/Home/Faqs.css
Labels: hacktoberfest-accepted, gssoc-ext, level1
